In [72]:
import numpy as np
alist=[1,2,3,4,5]
narray= np.array([6,7,8,9])
print(alist)
print(narray)

[1, 2, 3, 4, 5]
[6 7 8 9]


In [73]:
npmatrix=np.array([narray,narray,narray,narray])
print(npmatrix)

[[6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]]


In [105]:
print("Que-1 Create a Numpy array of size 4 x 5.")
fourbyfive=np.array([1,2,3,4,5])
fbyfmat=np.array([fourbyfive,fourbyfive,fourbyfive,fourbyfive])
print("Single array of five:")
print(fourbyfive)
print("Array coverstion from 1 by 5 to 4 by 5")
print(fbyfmat)

Que-1 Create a Numpy array of size 4 x 5.
Single array of five:
[1 2 3 4 5]
Array coverstion from 1 by 5 to 4 by 5
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [106]:
print("Que-2 Randomly initialize the array.")
print("Random number genraation:")
print("Here we will creat empty array so it will give random value to the array")
rdmnumarr=np.empty((1,4))
print(rdmnumarr)

Que-2 Randomly initialize the array.
Random number genraation:
Here we will creat empty array so it will give random value to the array
[[3.0e-323 3.5e-323 4.0e-323 4.4e-323]]


In [76]:
print("Que-3 Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.")
print("Created array:")
array=np.array([[1,0],[1,1]])
print(array)
print("Determinant of the created array:")
det= np.linalg.det(array)
print(int(det))
print("Transpose of the created array:")
print(array.T)

Que-3
Created array:
[[1 0]
 [1 1]]
Determinant of the created array:
1
Transpose of the created array:
[[1 1]
 [0 1]]


In [77]:
print("Que-4 Create another matrix of size 5 x 4 and randomly initialize it.")
import random
print("5 by 4 matrix with Randomly entered number:")
rndmat=np.empty((5,4))
for i in range(0,5):
    for j in range(0,4):
        n=random.randint(1,30)
        rndmat[i][j]=n;
print(rndmat)

Que-4
5 by 4 matrix with Randomly entered number:
[[13. 26.  5. 16.]
 [11. 30.  8.  7.]
 [30. 19.  3. 12.]
 [ 4. 28.  4.  6.]
 [ 7. 13.  4.  4.]]


In [78]:
print("Que-5 Perform Matrix multiplication.")
print("TO see better result i have taken identity to multiply:")
mulA=np.array([[1,1,1],[1,1,1],[1,1,1]])
mulB=np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Array A:")
print(mulA)
print("Array B:")
print(mulB)
res=np.dot(mulA,mulB)
print("Dot product:")
print(res)

Que-5
TO see better result i have taken identity to multiply:
Array A:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array B:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dot product:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [79]:
print("Que-6 Perform element wise matrix multiplication.")
print("TO see better result i have taken identity to multiply:")
mulA=np.array([[1,1,1],[1,1,1],[1,1,1]])
mulB=np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Array A:")
print(mulA)
print("Array B:")
print(mulB)
res=np.multiply(mulA, mulB)
print("Multiplication by elements:")
print(res)


Que-6
TO see better result i have taken identity to multiply:
Array A:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array B:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Multiplication by elements:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [80]:
print("Que-7 Find mean, median of the numpy array created.")
print(alist);
print(np.mean(alist));
print(np.median(alist));

Que-7 Find mean, median of the numpy array created.
[1, 2, 3, 4, 5]
3.0
3.0


In [81]:
print("Que-8 Obtain each row in the second column of the first array.")
print(npmatrix);
print(npmatrix[:, 1])

Que-8 Obtain each row in the second column of the first array.
[[6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]]
[7 7 7 7]


In [82]:
print("Que-9 Convert Numeric entries(columns) of Iris.csv to Mean Centered Ver")
#we can use pandas
import pandas as pd
data= pd.read_csv("/content/Iris.csv - Iris.csv.csv")
# arr=np.array(data)
data.drop('Id',axis='columns', inplace=True)
arr=data._get_numeric_data()
nparrayCentered = arr - np.mean(arr, axis=0) # Remove the mean for each column
print('Original matrix')
print(arr)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by column')
print(nparrayCentered.mean(axis=0))

Que-9 Convert Numeric entries(columns) of Iris.csv to Mean Centered Ver
Original matrix
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]
Centered by columns matrix
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.743333         0.446      -2.358667     -0.

In [83]:
print("Que-10 Study about numpy array attributes and implement it on the first matrix")
print("First array")
print(narray)
print("First attribute Shape:")
print (narray.shape)



Que-10 Study about numpy array attributes and implement it on the first matrix
First array
[6 7 8 9]
First attribute Shape:
(4,)


In [84]:
print("resize Shape:")
narray.shape=(2,2)
print(narray)

resize Shape:
[[6 7]
 [8 9]]


In [104]:
n=np.arange(12)
print ("Dimention of array",n.ndim)
print ("Array:",n)
b = n.reshape(3,4)
print("Size of array",b.size)
print ("Resize Array:")
print (b)
print("Datatype:",b.dtype)
print("ItemSize:",b.itemsize)
print (b.flags)

Dimention of array 1
Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Size of array 12
Resize Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Datatype: int64
ItemSize: 8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

