#DataLoader

In [70]:
import numpy as np
import torch

In [71]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [72]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [73]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [74]:
from torch.utils.data import TensorDataset

In [75]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [76]:
from torch.utils.data import DataLoader

In [77]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [78]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[103., 119.],
        [119., 133.],
        [ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.]])


#nn.Linear

In [79]:
import torch.nn as nn

In [80]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0142, -0.3348,  0.2377],
        [ 0.5558,  0.3503, -0.1736]], requires_grad=True)
Parameter containing:
tensor([-0.3669,  0.0026], requires_grad=True)


In [81]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0142, -0.3348,  0.2377],
         [ 0.5558,  0.3503, -0.1736]], requires_grad=True),
 Parameter containing:
 tensor([-0.3669,  0.0026], requires_grad=True)]

In [82]:
preds = model(inputs)
preds

tensor([[-13.6098,  56.5800],
        [-15.9035,  70.2947],
        [-32.6714,  85.2273],
        [ -7.4130,  65.3322],
        [-16.8436,  59.8282]], grad_fn=<AddmmBackward0>)

#loss Function

In [83]:
import torch.nn.functional as F

In [84]:
loss_fn = F.mse_loss

In [85]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(6017.6802, grad_fn=<MseLossBackward0>)


#Optimizer

In [86]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

##Train for multiple epochs

In [87]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [88]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 831.7863
Epoch [20/100], Loss: 607.5222
Epoch [30/100], Loss: 537.2523
Epoch [40/100], Loss: 477.7409
Epoch [50/100], Loss: 425.2939
Epoch [60/100], Loss: 379.0232
Epoch [70/100], Loss: 338.1925
Epoch [80/100], Loss: 302.1541
Epoch [90/100], Loss: 270.3376
Epoch [100/100], Loss: 242.2405


In [89]:
prediction = model(inputs)
prediction

tensor([[ 61.7310,  75.3147],
        [ 85.3430,  97.6688],
        [104.2192, 131.7373],
        [ 47.9783,  65.4639],
        [ 91.6083,  97.3153]], grad_fn=<AddmmBackward0>)

In [90]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [91]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[60.4592, 72.8715]], grad_fn=<AddmmBackward0>)