In [ ]:
import numpy as np
import torch

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [ ]:
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [ ]:
weight=torch.randn(2,3,requires_grad=True)
bias=torch.randn(2,requires_grad=True)

In [ ]:
inputs @ weight.t() + bias

tensor([[ -29.6389,  -97.8156],
        [ -52.0529, -133.6080],
        [ -79.8022, -217.2697],
        [  18.8939,  -37.4813],
        [ -83.6262, -161.3058]], grad_fn=<AddBackward0>)

In [ ]:
def model(inputs):
  return inputs @ weight.t()+bias

In [ ]:
prediction=model(inputs)
print(prediction)

tensor([[ -29.6389,  -97.8156],
        [ -52.0529, -133.6080],
        [ -79.8022, -217.2697],
        [  18.8939,  -37.4813],
        [ -83.6262, -161.3058]], grad_fn=<AddBackward0>)



# Loss Function



In [ ]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(35558.7109, grad_fn=<DivBackward0>)

In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(prediction, targets)
print(loss)

tensor(35558.7109, grad_fn=<DivBackward0>)


#Compute gradients

In [ ]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ -9769.8555, -12427.1289,  -7381.4302],
        [-16863.5020, -20436.4648, -12110.9668]])
tensor([-121.4453, -205.6961])


#Train moduel using gradient descent

In [ ]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(25056.2930, grad_fn=<DivBackward0>)


In [ ]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(1017.0349, grad_fn=<DivBackward0>)


In [ ]:
prediction

tensor([[ 67.0450,  67.7932],
        [ 80.2262,  89.1824],
        [107.3168,  85.7444],
        [ 76.8836,  82.1954],
        [ 66.0626,  78.5209]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])