
#Predication using gussionNB



In [105]:
#Import scikit-learn dataset library
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB

#Load dataset

iris =pd.read_csv('/content/Dataset1.csv') 
iris

Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N

In [106]:
le=preprocessing.LabelEncoder()
humidity=iris['Humidity']
outlook=iris['Outlook']
play=iris['Play']
temp=iris['Temp']
wind=iris['Wind']
humidity_encoded=le.fit_transform(humidity)
print("Humidity:",humidity_encoded)
outlook_encoded=le.fit_transform(outlook)
print("Outlook:",outlook_encoded)
play_encoded=le.fit_transform(play)
print("Play:",play_encoded)
temp_encoded=le.fit_transform(temp)
print("Temp:",temp_encoded)
wind_encoded=le.fit_transform(wind)
print("Weather:" ,wind_encoded)


Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]
Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Weather: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [115]:
onehotencoder=OneHotEncoder()
one_hot_temp=pd.get_dummies(iris["Temp"])

temp_cold_encoded=le.fit_transform(one_hot_temp['C'])
temp_hot_encoded=le.fit_transform(one_hot_temp['H'])
temp_mild_encoded=le.fit_transform(one_hot_temp['M'])
one_hot_temp

C  H  M
0   0  1  0
1   0  1  0
2   0  1  0
3   0  0  1
4   1  0  0
5   1  0  0
6   1  0  0
7   0  0  1
8   1  0  0
9   0  0  1
10  0  0  1
11  0  0  1
12  0  1  0
13  0  0  1

In [112]:
#features=tuple(zip(humidity_encoded,outlook_encoded,temp_encoded,wind_encoded))
features=tuple(zip(humidity_encoded,outlook_encoded,temp_cold_encoded,temp_hot_encoded,temp_mild_encoded,wind_encoded))

print("Features:",features)

Features: ((2, 1, 0, 1, 0, 0), (0, 1, 0, 1, 0, 1), (2, 0, 0, 1, 0, 0), (2, 2, 0, 0, 1, 0), (2, 2, 1, 0, 0, 0), (1, 2, 1, 0, 0, 1), (2, 0, 1, 0, 0, 1), (2, 1, 0, 0, 1, 0), (1, 1, 1, 0, 0, 0), (0, 2, 0, 0, 1, 0), (0, 1, 0, 0, 1, 1), (1, 0, 0, 0, 1, 1), (2, 0, 0, 1, 0, 0), (2, 2, 0, 0, 1, 1))


In [113]:
model=MultinomialNB()
model.fit(features,play)

MultinomialNB()

In [116]:
predicted=model.predict([[2,1,0,1,0,0]])#[[HUMIDITY=2,OUTLOOK=1,TEMP=2,WIND=0]] 
print("Predicted Valuse:",predicted)

Predicted Valuse: ['Y']


In [131]:
predicted1= model.predict([[0,2,0,0,1,1]])#[[HUMIDITY=0,OUTLOOK=2,TEMP=0,WIND=1]]
print("Predicted Value:", predicted1)

Predicted Value: ['Y']


#Train test spilit

In [122]:
data_train, data_test, target_train, target_test = train_test_split(features,play, test_size = 0.30, random_state = 11)

In [123]:
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [124]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.4


In [125]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[1, 0],
       [3, 1]])

In [126]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.25 1.  ]
recall: [1.   0.25]


# 80%20

In [155]:
data_train, data_test, target_train, target_test = train_test_split(features,play, test_size = 0.20)
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.3333333333333333


In [156]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 2],
       [0, 1]])

In [157]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.         0.33333333]
recall: [0. 1.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#For Multinomial

In [127]:
gnb=model
gnb.fit(data_train,target_train)

target_pred=gnb.predict(data_test)

In [128]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(target_test,target_pred))

Accuracy: 0.4


In [129]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[1, 0],
       [3, 1]])

In [130]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.25 1.  ]
recall: [1.   0.25]
